CREATE TABLE usuarios_usuario (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    first_name VARCHAR(150) NOT NULL DEFAULT '',
    last_name VARCHAR(150) NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    last_login TIMESTAMPTZ,
    date_joined TIMESTAMPTZ NOT NULL
);

CREATE TABLE tarefas_categoria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    criado_por_id BIGINT NOT NULL REFERENCES usuarios_usuario(id)
);

CREATE TABLE tarefas_tarefa (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(200) NOT NULL,
    descricao TEXT NOT NULL DEFAULT '',
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    prazo DATE,
    prioridade VARCHAR(5) NOT NULL DEFAULT 'media',
    criado_em TIMESTAMPTZ NOT NULL,
    categoria_id BIGINT REFERENCES tarefas_categoria(id) ON DELETE SET NULL,
    criado_por_id BIGINT NOT NULL REFERENCES usuarios_usuario(id)
);

CREATE TABLE tarefas_compartilhamentotarefa (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    permissao VARCHAR(7) NOT NULL DEFAULT 'leitura',
    tarefa_id BIGINT NOT NULL REFERENCES tarefas_tarefa(id),
    usuario_id BIGINT NOT NULL REFERENCES usuarios_usuario(id),
    UNIQUE (tarefa_id, usuario_id)
);

CREATE INDEX ON tarefas_tarefa (criado_por_id);
CREATE INDEX ON tarefas_tarefa (categoria_id);
CREATE INDEX ON tarefas_categoria (criado_por_id);
CREATE INDEX ON tarefas_compartilhamentotarefa (tarefa_id);
CREATE INDEX ON tarefas_compartilhamentotarefa (usuario_id);
